version: '2'
services:
  vernemq:
    image: erlio/docker-vernemq:1.5.0
    ports:
      - 1883:1883
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_log.console.level=debug